// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/darcops/boletia/internal/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// CurrencyService is an autogenerated mock type for the CurrencyService type
type CurrencyService struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: currency, startDate, endDate
func (_m *CurrencyService) GetHistory(currency string, startDate string, endDate string) ([]*domain.CurrenciesHistory, error) {
	ret := _m.Called(currency, startDate, endDate)

	var r0 []*domain.CurrenciesHistory
	if rf, ok := ret.Get(0).(func(string, string, string) []*domain.CurrenciesHistory); ok {
		r0 = rf(currency, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CurrenciesHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(currency, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
